### ISSUE TITLE
about ytid

### ISSUE THREAD

**Issue by Dingkx9** [rsmbyk/objects-that-sound#3]
hello,sir! I wanna know what ytid in the segment means.Thank u.

**Comment by rsmbyk** [comment]
It means "youtube id". It is the one given to watch parameter in its url. Usually in `https://www.youtube.com/watch?v=[ytid]`. You can get sample segments file at the [AudioSet download page](https://research.google.com/audioset/download.html) (I haven't put the segments file into the repo). They named it ytid. I just follow the terms they use.
